baseURL: https://jacquiswebsite.netlify.app/
languageCode: en-us
title: London Business School Website for Jacqui Cole
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      WELCOME TO LONDON BUSINESS SCHOOL. I AM AN EXECUTIVE MBA STUDENT
      INTERESTED IN APPLYING DATA ANALYTICS TO BUSINESS.
    title: Jacqui's Hub for Data Science with R
  blog: {Welcome to London Business School. I am an Executive MBA student 
  interested in applying data analytics to business using R.}
  contact:
    address:
      - city: London, NW1 4SA 
        country: United Kingdom
        street: Regent's park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jcole.embals2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0)20 7000 7000
        title: Phone
  custom_css: []
  custom_js: []
  description: Jacqui's Webpages about R
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: LBS
        text: 'London Business School'
        url: http://www.london.edu
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/AImaterials
  #\    - icon: fa-facebook
  #\      label: Facebook
  #\      url: https://www.facebook.com
  #\    - icon: fa-instagram
  #\      label: Instagram
  #\      url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/jacquicole
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jacqui-cole-204305240/
  image: 'None'
  name: Jacqui Cole
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Helpful Links
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: Data Science with R
    title: LBS
  tiles:
    enable: yes
    showcase:
      - image: Rhubimage.jpg
        subtitle: Coding Fun with R
        title: R Hub
        url: blogs/blog1
      - image: machine-learning-image.jpeg
        subtitle: Machine Learning with R
        title: ML Hub 
        url: blogs/blog2
      - image: datavistile.jpg
        subtitle: Data Visualisation with R
        title: Visualisation Hub
        url: blogs/blog3 # there's no blog3 anymore... 
      - image: analytics.jpg
        subtitle: Data Manipulation with R
        title: Data Manipulation Hub
        url: blogs/blog4
      - image: databases.jpg
        subtitle: Databases and Webscraping with R
        title: Databases Hub
        url: blogs/bloge #i wanted to make it blog 3, buttyped bloge... oh well
      - image: worldbusiness.jpg
        subtitle: Data Analytics for Global Business
        title: Data Analytics Hub
        url: blogs/risk_return
  two:
    buttonText: Helpful Links
    enable: yes
    subtitle: "Resources about Data Science for R"
    title: Helpful Links
    url: blogs
    
    
markup: 
  goldmark: 
    renderer: 
      unsafe: true
      
